### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by mackie90125** [MOLB7621/problem-set-2#1]
For problem 5, the answer given in class is chrY:28507239-59100456

However, the question asks for the longest interval on chr22.

When I run my code without sorting for only ch22, I do get the above answer. So is the given answer in class incorrect? Or should the question ask for the longest interval on any chromosome?

**Comment by jayhesselberth** [comment]
Yes it should be the longest on `chr22`, not `chrY`.

**Comment by jayhesselberth** [comment]
Travis tests updated. If you sync your fork you should have the new answers.

```
$ git remote add upstream https://github.com/MOLB7621/problem-set-2
$ git fetch upstream
$ git merge upstream/master
```

**Comment by ekmeredith** [comment]
Has Travis worked for anyone? I still can't get it to give me a pass.  I tried re-forking the problem set just in case the fork sync was the problem, but it didn't help.  I can see the new answers in the travis file. Is the problem that I have my extra credit answer #6 in my answers.yml file?

**Comment by mackie90125** [comment]
Travis is also not working for me. I deleted everything and re-cloned as well.

**Comment by jayhesselberth** [comment]
Travis should work now. Sync your fork and re-commit.
