### ISSUE TITLE
question #2

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/problem-set-2#2]
So i've figured out a few ways to get to the answer.  But I think my best bet now is: 
`$ echo -e "chr22\t19000000\t19000500" > tmp.bed | bedtools nuc -fi fasta/hg19.chr22.fa -bed tmp.bed`

However is there a way to do this without creating the bed file first?  I can't figure out how to use data instream "-" for the -bed option since it requires a bed file
I've tried using the
`-bed <(echo -e "chr22\t19000000\t19000500")`  but I get the error that a bed file is needed

**Comment by jayhesselberth** [comment]
I assume your first commands are really two parts; I don't think it would work in a pipe.

```
$ echo -e "chr22\t19000000\t19000500" > tmp.bed
$ bedtools nuc -fi fasta/hg19.chr22.fa -bed tmp.bed
```

BEDtools may not be set up to use process substitutions (i.e. `<(cmd)`).

**Comment by ericlarson84** [comment]
The pipe does work, but it's probably more appropriate to not pipe it.
thanks

**Comment by mackie90125** [comment]
This code works for me on Linux. It's strange that yours doesn't work.
```
$ bedtools nuc -fi hg19.chr22.fa -bed <(echo -e "chr22\t19000000\t19000500")
```

**Comment by jayhesselberth** [comment]
The proc substitution works on OS X too (not surprising). I thought you had tried it and had it fail.
