### ISSUE TITLE
Travis issues

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/problem-set-2#3]
I finished everything, and have all my answers output to answer.yml in the top level of problem-set-2.

Travis runs and I get "no answers.yml file"
I've tried running the test manually from the top level directory `bash .test/.tests.sh` and get the same result
However, if I manually enter the test directory and run the script,
`cd .test
bash .tests.sh`
there is no output at all, just a blank line.

anyone else having this issue with Travis?  It's probably a problem with me and not Travis, but I can't seem to figure out a solution.

**Comment by ericlarson84** [comment]
Saw there was a Travis update, so burned down, and re-forked.  
Still having the same issue

**Comment by jayhesselberth** [comment]
Travis should work now. Sync your fork and re-commit.
