### ISSUE TITLE
Permission denied on file 

### ISSUE THREAD

**Issue by stonedas** [MOLB7621/problem-set-2#30]
I am trying to answer question 4 and this is what I have for the answer in my answers.sh file. This seems to work when I type in the terminal but not in vim answers.sh. What's strange is that I get an answer out for 4 but I'm not sure what the error message means.

```bash
# answers.sh
promoter="$datasets/bed/tss.hg19.chr22.bed.gz"
signal= "$datasets/bedtools/ctcf.hela.chr22.bg.gz"
answer_4=$(bedtools map -c 4 -o median -a $promoter -b $signal | awk 'BEGIN {OFS="\t"} ($7 !=".")' | sort -k7gr | cut -f4 | head -n1)
```

```bash
$ bash answers.sh
answer-1: 6314
answer-3: 167
**answers.sh: line 38: /vol2/home/stonedas/data-sets/bedtools/ctcf.hela.chr22.bg.gz: Permission denied**
answer-4: PRAME
answer-5: chr22:49702164-49702704
chr22:49994584-49995124
```

**Comment by jayhesselberth** [comment]
You have a space in your answers.sh, I think that's the problem. If you enclose your code blocks in triple backticks it's easier to spot this stuff (see my edits to your post).

```bash
# yours
signal= "$datasets/bedtools/ctcf.hela.chr22.bg.gz"
# corrected
signal="$datasets/bedtools/ctcf.hela.chr22.bg.gz"

```

**Comment by stonedas** [comment]
I see it now, that fixed it! Thanks!
