### ISSUE TITLE
Problem Question 4 

### ISSUE THREAD

**Issue by fsantoriello** [MOLB7621/problem-set-2#35]
Hey,

Working on question 4 and not getting PRAME. I notice that if I simply run map with tss.hg19.chr22.bed.gz and ctcf.hela.chr22.bg.gz and -o median, I will get the correct answer as listed (PRAME). However, that doesn't line up with the question for me. We want the median signal across the promoter (1000 bp upstream of the TSS). If I generate a bed of 1000 bp intervals directly upstream of the tss and run the following:

bedtools map -a promoters.bed -b ctcf.hela.chr22.bg.gz -c 4 -o median

then sort that, the largest median I get is for TAB1 (median = 47). PRAME's median with this method is 11. 

Is my logic wrong? Any help is appreciated.

-Frank

**Comment by fsantoriello** [comment]
Also might be helpful... I'm considering 1000 bps upstream of the TSS to not include the TSS itself. 

Ex: TSS = 1001 , promoter = 1 - 1000

Is that my issue?

**Comment by kriemo** [comment]
The issue is likely with how you are defining upstream. For example if the TSS is on a negative stranded gene, which direction is upstream of the TSS? The `-s` option in `bedtools slop` will help you obtain the correct answer.

**Comment by fsantoriello** [comment]
Got it working. Thanks!
