### ISSUE TITLE
Travis running issue

### ISSUE THREAD

**Issue by cyfccc** [MOLB7621/problem-set-2#8]
Hi, I have some problem running Travis. I have added my run.sh and answers.yml files to git and pushed to origin master. But when I click the "build/failing" switch which directs me to Travis, Travis does not run but show "There is no build on the default branch yet" for problem-set-2 under my username. Is there anything I missed?

**Comment by jayhesselberth** [comment]
Easiest thing to do is submit a pull request, and Travis will build on that. If there are errors, subsequent commits in your repository will appear in the pull request.

If you want to have Travis build your commits without a pull request, you need to:

1. go to the travis page
1. click the `+` symbol next to "My Repositories"
1. click the "sync account" button
1. flip the switch for problem-set-2.

Commits will then trigger Travis builds at `https://travis-ci.org/cyfccc/problem-set-2`.

**Comment by cyfccc** [comment]
I did the same thing to flip the switch for problem-set-2. But it still shows "No builds for this repository" when I go to https://travis-ci.org/cyfccc/problem-set-2.

**Comment by jayhesselberth** [comment]
Did you commit after flipping the switch? That should trigger a build.

On Saturday, February 20, 2016, cyfccc <notifications@github.com> wrote:

> I did the same thing to flip the switch for problem-set-2. But it still
> shows "No builds for this repository" when I go to
> https://travis-ci.org/cyfccc/problem-set-2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MOLB7621/problem-set-2/issues/8#issuecomment-186657284>
> .
>


-- 
--
Jay Hesselberth
Assistant Professor
Biochemistry & Molecular Genetics
University of Colorado School of Medicine
off: (303) 724-5384
lab: (303) 724-5486
jay.hesselberth@gmail.com

**Comment by cyfccc** [comment]
I think I kind of figuring out what happened. I add, commit and push run.sh and answers.yml files before flipping the switch, which leads to that error. But when I flip at the beginning, it all goes on well.
